import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
} from "node:fs";
import { resolve, dirname } from "node:path";
import { converter, formatHex } from "culori";

export interface Tokens {
  color: any;
  font: any;
  icon: any;
}

// ---- Utilities ----

const __dirname = dirname(new URL(import.meta.url).pathname);
const toSrgb = converter("rgb");

export function loadTokens(repoRoot: string): Tokens {
  return JSON.parse(readFileSync(resolve(repoRoot, "tokens.json"), "utf8"));
}

export function writeIfChanged(absPath: string, content: string | Buffer): boolean {
  mkdirSync(dirname(absPath), { recursive: true });
  if (existsSync(absPath)) {
    const existing = readFileSync(absPath);
    const next = typeof content === "string" ? Buffer.from(content, "utf8") : content;
    if (existing.equals(next)) return false;
  }
  writeFileSync(absPath, content);
  return true;
}

// ---- Color conversion ----

export function oklchStringToHex(s: string): string {
  const m = s.match(/oklch\(([\d.]+)%\s+([\d.]+)\s+(\d+)\)/);
  if (!m) throw new Error(`Cannot parse OKLCH string: ${s}`);
  const [, L, C, H] = m;
  const c = toSrgb({
    mode: "oklch",
    l: parseFloat(L) / 100,
    c: parseFloat(C),
    h: parseFloat(H),
  });
  if (!c) throw new Error(`Out of gamut for ${s}`);
  return formatHex(c).toUpperCase();
}

export function brandHex(t: Tokens): string {
  const { lightness, chroma, hue } = t.color.brand.oklch;
  return formatHex(
    toSrgb({ mode: "oklch", l: lightness, c: chroma, h: hue })!,
  ).toUpperCase();
}

export function brandForegroundHex(light: "light" | "dark", t: Tokens): string {
  return oklchStringToHex(t.color.brand[light].foreground);
}

function hexToRgbNormalized(hex: string): { red: number; green: number; blue: number } {
  const h = hex.replace("#", "");
  return {
    red: parseInt(h.slice(0, 2), 16) / 255,
    green: parseInt(h.slice(2, 4), 16) / 255,
    blue: parseInt(h.slice(4, 6), 16) / 255,
  };
}

function oklchStringToColorKt(s: string): string {
  return `Color(0xFF${oklchStringToHex(s).replace("#", "")})`;
}

// ---- CSS (web) ----

export function generateBrandTokensCSS(t: Tokens): string {
  const fb = (f: any) =>
    `${f.family}, ${f.fallbacks.map((s: string) => s).join(", ")}`;
  const surface = (m: any) =>
    Object.entries(m)
      .map(([k, v]) => `      --wa-color-surface-${k}: ${v};`)
      .join("\n");
  const text = (m: any) =>
    Object.entries(m)
      .map(([k, v]) => `      --wa-color-text-${k}: ${v};`)
      .join("\n");

  const brandLine = `${t.color.brand.oklch.lightness * 100}% ${t.color.brand.oklch.chroma} ${t.color.brand.oklch.hue}`;

  const accentHue = t.color.brand.accent?.oklch?.hue ?? 45;
  const accentChroma = t.color.brand.accent?.oklch?.chroma ?? 0.08;
  const accentLightness = t.color.brand.accent?.oklch?.lightness ?? 0.45;
  const accentLine = `${accentLightness * 100}% ${accentChroma} ${accentHue}`;

  return `/* GENERATED by livtet-branding — do not edit by hand. */

@layer wa-color-palette, wa-theme-overrides;

@layer wa-color-palette {
  :where(:root),
  .wa-palette-livtet {
    :where(:root:not([data-theme="dark"]):not(.wa-dark)) & {
${surface(t.color.surface.light)}
    }

    :where([data-theme="dark"], .wa-dark) & {
${surface(t.color.surface.dark)}
    }

    :where(:root:not([data-theme="dark"]):not(.wa-dark)) & {
${text(t.color.text.light)}
    }

    :where([data-theme="dark"], .wa-dark) & {
${text(t.color.text.dark)}
    }
  }
}

@layer wa-theme-overrides {
  :where(:root),
  .wa-palette-livtet {
    --wa-color-brand-95: oklch(93% 0.04 158);
    --wa-color-brand-90: oklch(85% 0.08 158);
    --wa-color-brand-80: oklch(72% 0.11 158);
    --wa-color-brand-70: oklch(60% 0.12 158);
    --wa-color-brand-60: oklch(50% 0.12 158);
    --wa-color-brand-50: oklch(${brandLine});
    --wa-color-brand-40: oklch(35% 0.08 158);
    --wa-color-brand-30: oklch(28% 0.06 158);
    --wa-color-brand-20: oklch(20% 0.05 158);
    --wa-color-brand-10: oklch(12% 0.03 158);
    --wa-color-brand-05: oklch(8% 0.02 158);
    --wa-color-brand: var(--wa-color-brand-50);

    --wa-color-accent-95: oklch(93% 0.03 ${accentHue});
    --wa-color-accent-90: oklch(85% 0.06 ${accentHue});
    --wa-color-accent-80: oklch(72% 0.08 ${accentHue});
    --wa-color-accent-70: oklch(60% 0.09 ${accentHue});
    --wa-color-accent-60: oklch(50% 0.09 ${accentHue});
    --wa-color-accent-50: oklch(${accentLine});
    --wa-color-accent-40: oklch(35% 0.07 ${accentHue});
    --wa-color-accent-30: oklch(28% 0.05 ${accentHue});
    --wa-color-accent-20: oklch(20% 0.04 ${accentHue});
    --wa-color-accent-10: oklch(12% 0.03 ${accentHue});
    --wa-color-accent-05: oklch(8% 0.02 ${accentHue});
    --wa-color-accent: var(--wa-color-accent-50);

    --wa-color-accent-fill-quiet: var(--wa-color-accent-95);
    --wa-color-accent-fill-normal: var(--wa-color-accent-90);
    --wa-color-accent-fill-loud: var(--wa-color-accent-50);
    --wa-color-accent-border-quiet: var(--wa-color-accent-90);
    --wa-color-accent-border-normal: var(--wa-color-accent-80);
    --wa-color-accent-border-loud: var(--wa-color-accent-60);
    --wa-color-accent-on-quiet: var(--wa-color-accent-40);
    --wa-color-accent-on-normal: var(--wa-color-accent-30);
    --wa-color-accent-on-loud: var(--wa-color-accent-05);
  }

  .wa-brand-accent {
    --wa-color-brand-key: 50;
    --wa-color-brand: var(--wa-color-accent-50);
    --wa-color-brand-fill-quiet: var(--wa-color-accent-95);
    --wa-color-brand-fill-normal: var(--wa-color-accent-90);
    --wa-color-brand-fill-loud: var(--wa-color-accent-50);
    --wa-color-brand-border-quiet: var(--wa-color-accent-90);
    --wa-color-brand-border-normal: var(--wa-color-accent-80);
    --wa-color-brand-border-loud: var(--wa-color-accent-60);
    --wa-color-brand-on-quiet: var(--wa-color-accent-40);
    --wa-color-brand-on-normal: var(--wa-color-accent-30);
    --wa-color-brand-on-loud: var(--wa-color-accent-05);
  }

  :where(:root),
  .wa-theme-default,
  .wa-light,
  .wa-dark,
  .wa-invert,
  .wa-palette-livtet {
    --wa-border-radius-scale: 0.25;
    --wa-font-family-body: ${fb(t.font.body)};
    --wa-font-family-heading: ${fb(t.font.heading)};
    --wa-font-family-code: ${fb(t.font.code)};
  }
}
`;
}

function semanticCssBlock(t: Tokens, color: string): string {
  const c = (t.color.semantic as any)[color];
  const baseHue = c.oklch.hue;
  return `  --wa-color-${color}-foreground-light: ${c.light.foreground};
  --wa-color-${color}-background-light: ${c.light.background};
  --wa-color-${color}-border-light: ${c.light.border};
  --wa-color-${color}-foreground-dark: ${c.dark.foreground};
  --wa-color-${color}-background-dark: ${c.dark.background};
  --wa-color-${color}-border-dark: ${c.dark.border};
  --wa-color-${color}-95: oklch(93% 0.04 ${baseHue});
  --wa-color-${color}-90: oklch(85% 0.08 ${baseHue});
  --wa-color-${color}-80: oklch(72% 0.11 ${baseHue});
  --wa-color-${color}-70: oklch(60% 0.12 ${baseHue});
  --wa-color-${color}-60: oklch(50% 0.12 ${baseHue});
  --wa-color-${color}-50: oklch(${c.oklch.lightness * 100}% ${c.oklch.chroma} ${baseHue});
  --wa-color-${color}-40: oklch(35% 0.08 ${baseHue});
  --wa-color-${color}-30: oklch(28% 0.06 ${baseHue});
  --wa-color-${color}-20: oklch(20% 0.05 ${baseHue});
  --wa-color-${color}-10: oklch(12% 0.03 ${baseHue});
  --wa-color-${color}-05: oklch(8% 0.02 ${baseHue});

    :where(:root:not([data-theme="dark"]):not(.wa-dark)) & {
      --wa-color-${color}-foreground: ${c.light.foreground};
      --wa-color-${color}-background: ${c.light.background};
      --wa-color-${color}-border: ${c.light.border};
    }

    :where([data-theme="dark"], .wa-dark) & {
      --wa-color-${color}-foreground: ${c.dark.foreground};
      --wa-color-${color}-background: ${c.dark.background};
      --wa-color-${color}-border: ${c.dark.border};
    }`;
}

export function generateSemanticColorsCSS(t: Tokens): string {
  const semanticColors = ["informational", "success", "warning", "danger"] as const;
  const blocks = semanticColors.map((color) => semanticCssBlock(t, color)).join("\n\n");
  return `/* GENERATED by livtet-branding — do not edit by hand. */

@layer wa-color-palette {
  :where(:root),
  .wa-palette-livtet {
${blocks}
  }
}
`;
}

// ---- Android ----

function surfaceBlock(t: Tokens, mode: "light" | "dark"): string {
  return Object.entries(t.color.surface[mode])
    .map(([k, v]) => {
      const name = k.charAt(0).toUpperCase() + k.slice(1);
      return `        val ${name} = ${oklchStringToColorKt(v as string)}`;
    })
    .join("\n");
}

function semanticBlock(t: Tokens): string {
  const semanticColors = ["informational", "success", "warning", "danger"] as const;
  const out: string[] = [];
  for (const color of semanticColors) {
    const c = (t.color.semantic as any)[color];
    const name = color.charAt(0).toUpperCase() + color.slice(1);
    out.push(
      `    val ${name} = ${oklchStringToColorKt(`oklch(${c.oklch.lightness * 100}% ${c.oklch.chroma} ${c.oklch.hue})`)}`,
    );
  }
  return out.join("\n") + "\n";
}

function semanticVariantsBlock(t: Tokens): string {
  const semanticColors = ["informational", "success", "warning", "danger"] as const;
  const out: string[] = [];
  for (const color of semanticColors) {
    const c = (t.color.semantic as any)[color];
    const name = color.charAt(0).toUpperCase() + color.slice(1);
    out.push(`    object ${name}Light {
        val Foreground = ${oklchStringToColorKt(c.light.foreground)}
        val Background = ${oklchStringToColorKt(c.light.background)}
        val Border = ${oklchStringToColorKt(c.light.border)}
    }
    object ${name}Dark {
        val Foreground = ${oklchStringToColorKt(c.dark.foreground)}
        val Background = ${oklchStringToColorKt(c.dark.background)}
        val Border = ${oklchStringToColorKt(c.dark.border)}
    }`);
  }
  return out.join("\n\n");
}

export function generateAndroidKotlin(t: Tokens): string {
  const brandKt = oklchStringToColorKt(
    `oklch(${t.color.brand.oklch.lightness * 100}% ${t.color.brand.oklch.chroma} ${t.color.brand.oklch.hue})`,
  );

  const fontResName = (key: string) =>
    (t.font[key as keyof typeof t.font] as any).fontsource.replace(/-/g, "_");

  const schemeKt = (mode: "light" | "dark") => {
    const S = `Surface${mode === "light" ? "Light" : "Dark"}`;
    const T = `Text${mode === "light" ? "Light" : "Dark"}`;
    const isLight = mode === "light";
    return `    primary               = LivtetColors.Brand,
    onPrimary             = LivtetColors.${T}.Normal,
    primaryContainer      = LivtetColors.${S}.Highlighted,
    onPrimaryContainer    = LivtetColors.${T}.Normal,
    secondary             = LivtetColors.Informational,
    onSecondary           = LivtetColors.${T}.Normal,
    secondaryContainer    = LivtetColors.Semantic.Informational${mode === "light" ? "Light" : "Dark"}.Background,
    onSecondaryContainer  = LivtetColors.Semantic.Informational${mode === "light" ? "Light" : "Dark"}.Foreground,
    tertiary              = LivtetColors.Success,
    onTertiary            = LivtetColors.${T}.Normal,
    tertiaryContainer     = LivtetColors.Semantic.Success${mode === "light" ? "Light" : "Dark"}.Background,
    onTertiaryContainer   = LivtetColors.Semantic.Success${mode === "light" ? "Light" : "Dark"}.Foreground,
    background            = LivtetColors.${S}.Default,
    onBackground          = LivtetColors.${T}.Normal,
    surface               = LivtetColors.${S}.Default,
    onSurface             = LivtetColors.${T}.Normal,
    surfaceVariant        = LivtetColors.${S}.Raised,
    onSurfaceVariant      = LivtetColors.${T}.Quiet,
    surfaceTint           = LivtetColors.Brand,
    inverseSurface        = LivtetColors.${isLight ? "SurfaceDark" : "SurfaceLight"}.Default,
    inverseOnSurface      = LivtetColors.${isLight ? "TextDark" : "TextLight"}.Normal,
    inversePrimary        = LivtetColors.${S}.Highlighted,
    error                 = LivtetColors.Danger,
    onError               = LivtetColors.Semantic.Danger${mode === "light" ? "Light" : "Dark"}.Foreground,
    errorContainer        = LivtetColors.Semantic.Danger${mode === "light" ? "Light" : "Dark"}.Background,
    onErrorContainer      = LivtetColors.Semantic.Danger${mode === "light" ? "Light" : "Dark"}.Foreground,
    outline               = LivtetColors.${S}.Border,
    outlineVariant        = LivtetColors.${S}.Border,
    scrim                 = LivtetColors.${isLight ? "SurfaceDark" : "SurfaceLight"}.Default,`;
  };

  return `package net.olamaelcu.livtet.branding

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight

// GENERATED by livtet-branding — do not edit by hand.

object LivtetColors {
    val Brand = ${brandKt}
${semanticBlock(t)}
    object Semantic {
${semanticVariantsBlock(t)}
    }

    object SurfaceLight {
${surfaceBlock(t, "light")}
    }
    object SurfaceDark {
${surfaceBlock(t, "dark")}
    }

    object TextLight {
        val Normal = ${oklchStringToColorKt(t.color.text.light.normal)}
        val Quiet  = ${oklchStringToColorKt(t.color.text.light.quiet)}
        val Link   = ${oklchStringToColorKt(t.color.text.light.link)}
    }
    object TextDark {
        val Normal = ${oklchStringToColorKt(t.color.text.dark.normal)}
        val Quiet  = ${oklchStringToColorKt(t.color.text.dark.quiet)}
        val Link   = ${oklchStringToColorKt(t.color.text.dark.link)}
    }
}

val BodyFamily    = FontFamily(Font(R.font.${fontResName("body")},    FontWeight.Normal))
val HeadingFamily = FontFamily(Font(R.font.${fontResName("heading")}, FontWeight.Medium))
val CodeFamily    = FontFamily(Font(R.font.${fontResName("code")},    FontWeight.Normal))

fun livtetLightColorScheme() = lightColorScheme(
${schemeKt("light")}
)

fun livtetDarkColorScheme() = darkColorScheme(
${schemeKt("dark")}
)
`;
}

export function generateAndroidXml(t: Tokens): string {
  const brand = brandHex(t);
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by livtet-branding — do not edit by hand. -->
<resources>
    <color name="ic_launcher_background">${brand}</color>
    <color name="brand">${brand}</color>
</resources>
`;
}

export function generateFontFamilyXml(fontRefName: string): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by livtet-branding — do not edit by hand. -->
<font-family xmlns:android="http://schemas.android.com/apk/res-auto">
    <font android:font="@font/${fontRefName}" android:fontWeight="400" />
</font-family>
`;
}

// ---- iOS ----

export function generateColorsetContentsJson(
  name: string,
  lightHex: string,
  darkHex: string,
): any {
  return {
    colors: [
      {
        color: {
          "color-space": "srgb",
          components: { ...hexToRgbNormalized(lightHex), alpha: "1.000" },
        },
        idiom: "universal",
      },
      {
        color: {
          "color-space": "srgb",
          components: { ...hexToRgbNormalized(darkHex), alpha: "1.000" },
        },
        idiom: "universal",
        appearances: [{ appearance: "luminosity", value: "dark" }],
      },
    ],
    info: { version: 1, author: "xcode" },
  };
}

export function generateIOSSwiftColorExt(t: Tokens): string {
  return `// GENERATED by livtet-branding — do not edit by hand.
import SwiftUI
import UIKit

public extension Color {
    static let brand: Color = Color("brand")
}

public extension UIColor {
    static var brand: UIColor { UIColor(named: "brand")! }
}
`;
}

export function generateIOSSwiftFontExt(t: Tokens): string {
  const familyNameMap: Record<string, string> = {
    "Work Sans": "Work Sans",
    "Geist Variable": "Geist",
    "JetBrains Mono": "JetBrains Mono",
  };
  const postScriptMap: Record<string, string> = {
    "Work Sans": "WorkSans-Regular",
    "Geist Variable": "Geist-Regular",
    "JetBrains Mono": "JetBrainsMono-Regular",
  };
  const familyName = (f: any) => familyNameMap[f.family] ?? f.family;
  const postScriptName = (f: any) => postScriptMap[f.family] ?? `${f.family.replace(/\s+/g, "")}-Regular`;
  return `// GENERATED by livtet-branding — do not edit by hand.
import SwiftUI
import UIKit

public extension Font {
    static func livtetBody(size: CGFloat = 16, weight: Font.Weight = .regular) -> Font {
        .custom("${familyName(t.font.body)}", size: size, relativeTo: .body).weight(weight)
    }
    static func livtetHeading(size: CGFloat = 24, weight: Font.Weight = .semibold) -> Font {
        .custom("${familyName(t.font.heading)}", size: size, relativeTo: .title).weight(weight)
    }
    static func livtetCode(size: CGFloat = 14) -> Font {
        .custom("${familyName(t.font.code)}", size: size, relativeTo: .body)
    }
}

public extension UIFont {
    static func livtetBody(size: CGFloat = 16) -> UIFont {
        UIFont(name: "${postScriptName(t.font.body)}", size: size) ?? .systemFont(ofSize: size)
    }
    static func livtetCode(size: CGFloat = 14) -> UIFont {
        UIFont(name: "${postScriptName(t.font.code)}", size: size) ?? .monospacedSystemFont(ofSize: size, weight: .regular)
    }
}
`;
}

// ---- Font downloading ----

function fontsourcePackageName(id: string, scope?: string): string {
  if (scope === "fontsource-variable") {
    return `@fontsource-variable/${id}`;
  }
  return `@fontsource/${id}`;
}

export function buildFontDownloadUrl(
  fontsourceId: string,
  familyName: string,
): string {
  const dir = fontsourceId.replace(/-/g, "");
  const familyFile = familyName.replace(/\s+/g, "");
  const raw = `https://raw.githubusercontent.com/google/fonts/main/ofl/${dir}/${familyFile}[wght].ttf`;
  return encodeURI(raw);
}

async function downloadIfChanged(url: string, absPath: string): Promise<boolean> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return writeIfChanged(absPath, buf);
}

export async function downloadFontsToDirs(
  t: Tokens,
  targets: Record<string, string[]>,
  nodeModulesRoot: string,
): Promise<void> {
  for (const [key, dirs] of Object.entries(targets)) {
    const f = t.font[key as keyof typeof t.font] as any;
    const metaPath = resolve(
      nodeModulesRoot,
      `${fontsourcePackageName(f.fontsource, f.scope)}/metadata.json`,
    );
    const meta = JSON.parse(readFileSync(metaPath, "utf8"));
    const url = buildFontDownloadUrl(meta.id, meta.family);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    const androidName = f.fontsource.replace(/-/g, "_");
    const filename = `${androidName}.ttf`;
    for (const dir of dirs) {
      mkdirSync(dir, { recursive: true });
      const absPath = resolve(dir, filename);
      const changed = writeIfChanged(absPath, buf);
      if (changed) console.log(`  wrote ${filename} to ${dir}`);
    }
  }
}
