// GENERATED by livtet-branding — do not edit by hand.
import SwiftUI
import UIKit

public extension Color {
    static let brand: Color = Color("brand")
}

public extension UIColor {
    static var brand: UIColor { UIColor(named: "brand")! }
}
