// GENERATED by livtet-branding — do not edit by hand.
import SwiftUI
import UIKit

public extension Font {
    static func livtetBody(size: CGFloat = 16, weight: Font.Weight = .regular) -> Font {
        .custom("Work Sans", size: size, relativeTo: .body).weight(weight)
    }
    static func livtetHeading(size: CGFloat = 24, weight: Font.Weight = .semibold) -> Font {
        .custom("Lora", size: size, relativeTo: .title).weight(weight)
    }
    static func livtetCode(size: CGFloat = 14) -> Font {
        .custom("JetBrains Mono", size: size, relativeTo: .body)
    }
}

public extension UIFont {
    static func livtetBody(size: CGFloat = 16) -> UIFont {
        UIFont(name: "WorkSans-Regular", size: size) ?? .systemFont(ofSize: size)
    }
    static func livtetCode(size: CGFloat = 14) -> UIFont {
        UIFont(name: "JetBrainsMono-Regular", size: size) ?? .monospacedSystemFont(ofSize: size, weight: .regular)
    }
}
